name: Download datasets (daily)

on:
  schedule:
    - cron: 20 23 * * *

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Download data
      run: |
        python download_datasets.py

    - name: Git Config
      run: |
        git config user.name 'Nya Îžlimu'
        git config user.email 'info@elimu.ai'
    - name: Git Commit
      run: |
        git add **/*.csv
        git commit -m 'chore(ml): download datasets' --allow-empty
    - name: Git Push
      run: |
        git push
