name: Download datasets (daily)

on:
  schedule:
    - cron: 20 23 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Download data
      run: |
        python download_datasets.py

    - name: GitHub Actor
      env: 
        GITHUB_ACTOR: ${{ github.actor }}   
      run: echo "$GITHUB_ACTOR"

    - name: GitHub Triggering Actor
      env: 
        GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}   
      run: echo "$GITHUB_TRIGGERING_ACTOR"

    - name: Git Config
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Git Generate Short Diffstat
      run: |
        git --no-pager diff --shortstat

    - name: Git Dry Run
      run: git add -n '**/*.csv'
    
    - name: Git Commit
      run: |
        git add '**/*.csv'
        git commit -m 'chore(ml): download datasets' --allow-empty

    - name: Git Pull
      run: |
        git fetch
        git pull

    - name: Git Push
      run: |
        git push
